### ISSUE TITLE
Update DooSoftware projects to newest versions

### ISSUE THREAD

**Issue by anuwish** [e5-tu-do/DooCore#3]
Some developments have happened in the private e5 repository. These need to be merged.

**Comment by Frankenfrog** [comment]
Done for all branches for which I have the permission. @anuwish I can't push to the master. Can you please either give me the required permission or do it by yourself.

**Comment by anuwish** [comment]
You need to push to a branch and open a merge/pull request. Then anybody in the @e5-tu-do/doosoftware team can accept that merge request, I believe.

**Comment by Frankenfrog** [comment]
Finished!
